# NOME DO PIPELINE IGUAL AO NOME DO ARQUIVO (SEM ".yml")
# altere as linhas 8, 9, 10, 11, 23 e 24
resources:
  repositories:
    - repository: self
      trigger: none
variables:
  azureServiceConnection: 'azure-connection'
  subscriptionId: '<Sua SubscriptionID aqui>'
  resourceGroup: '<Seu Resource Group aqui>'
  location: '<Sua Localidade/Região aqui>'
  
  imageRepository: 'eshoponweb/web'
  dockerfilePath: 'src/Web/Dockerfile' 
  AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL: true

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    pool:
      name: <Seu Agent Pool aqui>
      demands: Agent.Name -equals <Seu Agent Name aqui>
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ACR using Bicep'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/acr.bicep'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'outputJson'

    - task: PowerShell@2
      displayName: 'Parse Bicep Output for ACR Login Server'
      name: BicepOutput
      inputs:
        targetType: 'inline'
        script: |
          $jsonOutput = '$(outputJson)' | ConvertFrom-Json
          $loginServer = $jsonOutput.acrLoginServer.value
          Write-Host "ACR Login Server: $loginServer"
          Write-Host "##vso[task.setvariable variable=acrLoginServer;isOutput=true;]$loginServer"

    - task: AzureCLI@2
      displayName: 'Dynamic Login to ACR'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $loginServerValue = "$(BicepOutput.acrLoginServer)"
          $acrName = $loginServerValue.Split('.')[0]
          Write-Host "Getting access token for ACR: $acrName"
          $accessToken = az acr login --name $acrName --expose-token --output tsv --query accessToken
          $accessToken | docker login $loginServerValue --username 00000000-0000-0000-0000-000000000000 --password-stdin
          Write-Host "Docker login successful."

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: '$(BicepOutput.acrLoginServer)/$(imageRepository)'
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: 'Push Docker image to ACR'
      inputs:
        command: push
        repository: '$(BicepOutput.acrLoginServer)/$(imageRepository)'
        tags: |
          $(Build.BuildId)
          latest
